openapi: 3.0.3
info:
  title: Inventory management
  version: 0.0.0
  description:
    The Inventory Management System API allows businesses         to efficiently
    manage their stock of products. This API provides endpoints         for creating,
    reading, updating, and deleting (CRUD) inventory items.            It uses JSON
    Web Tokens (JWT) for secure authentication.
paths:
  /:
    get:
      operationId: root_retrieve
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          description: No response body
  /api/auth/login/:
    post:
      operationId: api_auth_login_create
      description: Function to login user
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          description: No response body
  /api/auth/logout/:
    post:
      operationId: api_auth_logout_create
      tags:
        - api
      responses:
        '200':
          description: No response body
  /api/auth/register/:
    post:
      operationId: api_auth_register_create
      description: Register a new user.
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          description: No response body
  /api/mgmt/inventory/:
    get:
      operationId: api_mgmt_inventory_retrieve
      tags:
        - api
      responses:
        '200':
          description: No response body
    post:
      operationId: api_mgmt_inventory_create
      tags:
        - api
      responses:
        '200':
          description: No response body
    put:
      operationId: api_mgmt_inventory_update
      tags:
        - api
      responses:
        '200':
          description: No response body
    delete:
      operationId: api_mgmt_inventory_destroy
      tags:
        - api
      responses:
        '204':
          description: No response body
  /api/mgmt/inventory/{id}/:
    get:
      operationId: api_mgmt_inventory_retrieve_2
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      tags:
        - api
      responses:
        '200':
          description: No response body
    post:
      operationId: api_mgmt_inventory_create_2
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      tags:
        - api
      responses:
        '200':
          description: No response body
    put:
      operationId: api_mgmt_inventory_update_2
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      tags:
        - api
      responses:
        '200':
          description: No response body
    delete:
      operationId: api_mgmt_inventory_destroy_2
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      tags:
        - api
      responses:
        '204':
          description: No response body
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
        - in: query
          name: format
          schema:
            type: string
            enum:
              - json
              - yaml
        - in: query
          name: lang
          schema:
            type: string
            enum:
              - af
              - ar
              - ar-dz
              - ast
              - az
              - be
              - bg
              - bn
              - br
              - bs
              - ca
              - ckb
              - cs
              - cy
              - da
              - de
              - dsb
              - el
              - en
              - en-au
              - en-gb
              - eo
              - es
              - es-ar
              - es-co
              - es-mx
              - es-ni
              - es-ve
              - et
              - eu
              - fa
              - fi
              - fr
              - fy
              - ga
              - gd
              - gl
              - he
              - hi
              - hr
              - hsb
              - hu
              - hy
              - ia
              - id
              - ig
              - io
              - is
              - it
              - ja
              - ka
              - kab
              - kk
              - km
              - kn
              - ko
              - ky
              - lb
              - lt
              - lv
              - mk
              - ml
              - mn
              - mr
              - ms
              - my
              - nb
              - ne
              - nl
              - nn
              - os
              - pa
              - pl
              - pt
              - pt-br
              - ro
              - ru
              - sk
              - sl
              - sq
              - sr
              - sr-latn
              - sv
              - sw
              - ta
              - te
              - tg
              - th
              - tk
              - tr
              - tt
              - udm
              - ug
              - uk
              - ur
              - uz
              - vi
              - zh-hans
              - zh-hant
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
