# Generated by Django 5.1.1 on 2024-10-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_mgmt', '0002_alter_inventory_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table=None,
        ),
    ]
