# Generated by Django 5.1.1 on 2024-10-04 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('inventory_mgmt', '0003_alter_inventory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser'),
            preserve_default=False,
        ),
    ]
